### ISSUE TITLE
Alignment on list titles

### ISSUE THREAD

**Issue by drewsamsen** [taylorpoe/monotab#20]
If I edit the list title down to an empty string it suddenly left aligns in the column header http://d.pr/i/1i0aG

**Comment by taylorpoe** [comment]
@drewsamsen Ah yeah, nice catch.

**Comment by taylorpoe** [comment]
Using the odd `<spancontenteditable="true"></span>` to get this to float in the center rather than a normal input. Might need to switch back to a normal input and flexbox it with the count indicator. Not sure.
